name: tests

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  tests:
    name: tests
    runs-on: self-hosted
    steps:
    - name: Ensure workspace ownership
      run: echo "chown -R $USER $GITHUB_WORKSPACE" && sudo chown -R $USER $GITHUB_WORKSPACE

    - name: Check out code
      uses: actions/checkout@v4
