name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
    - name: Ensure workspace ownership
      run: echo "chown -R $USER $GITHUB_WORKSPACE" && sudo chown -R $USER $GITHUB_WORKSPACE

    - name: Check out code
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.MY_DEPLOY_KEY }}
